$iDIR="$HOME/.config/swaync/images/ja.png"

general {
    before_sleep_cmd = loginctl lock-session    # ensures that the session is locked before going to sleep
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Warn
listener {
    timeout = 300 # 5 min
    on-timeout = brightnessctl -s set 10 && notify-send -i $iDIR " You are idle!" 
    on-resume = brightnessctl -r && notify-send -i $iDIR " Oh! you're Back" " Hello !!!"
}

# Screenlock
listener {
    timeout = 360 # 6 min
    on-timeout = loginctl lock-session # command to run when timeout has passed
}

listener {
    timeout = 390 # 6.5 min
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}

listener {
    timeout = 480 # 8 min
    on-timeout = systemctl suspend
}

# Turn off screen 
# (disabled by default)
# listener {
#     timeout = 630                            # 10.5 min
#     on-timeout = hyprctl dispatch dpms off  # command to run when timeout has passed
#     on-resume = hyprctl dispatch dpms on    # command to run when activity is detected after timeout has fired.
# }

# Suspend # disabled by default
# listener {
   # timeout = 1200                            # 20 min
   # on-timeout = systemctl suspend # command to run when timeout has passed
    # on-resume = notify-send -i $iDIR " Oh! you're back" "Hello !!!"  # command to run when activity is detected after timeout has fired.
# }
