# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(292732)
$foreground = rgb(F9E5E9)
$color0 = rgb(4F4C58)
$color1 = rgb(1C1842)
$color2 = rgb(455E9B)
$color3 = rgb(7C6496)
$color4 = rgb(7F6495)
$color5 = rgb(7F6495)
$color6 = rgb(B2878F)
$color7 = rgb(EED1D7)
$color8 = rgb(A69296)
$color9 = rgb(252058)
$color10 = rgb(5C7ECF)
$color11 = rgb(A586C8)
$color12 = rgb(AA86C7)
$color13 = rgb(AA86C7)
$color14 = rgb(EDB4BF)
$color15 = rgb(EED1D7)
