# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(2A2A2A)
$foreground = rgb(E8E8E8)
$color0 = rgb(4F4F4F)
$color1 = rgb(292929)
$color2 = rgb(292929)
$color3 = rgb(2C2C2C)
$color4 = rgb(565656)
$color5 = rgb(5C5C5C)
$color6 = rgb(8E8F8F)
$color7 = rgb(D6D6D6)
$color8 = rgb(969696)
$color9 = rgb(363636)
$color10 = rgb(373737)
$color11 = rgb(3B3B3B)
$color12 = rgb(727272)
$color13 = rgb(7B7B7B)
$color14 = rgb(BEBEBE)
$color15 = rgb(D6D6D6)
