volume=40
# Enable cache
cache=yes
# Use a large 1GB RAM cache (adjust based on your RAM)
demuxer-max-bytes=1024MiB
demuxer-max-back-bytes=512MiB
# Force mpv to seek ahead and fill the cache
cache-secs=300

#vo=gpu-next
#gpu-api=vulkan
#gpu-context=waylandvk
#target-colorspace-hint=auto
